homer = Member.create!(name: 'Homer', website_url: 'https://www.everlywell.com/blog/sleep-and-stress/migraines-possible-causes/')
marge = Member.create!(name: 'Marge', website_url: 'https://www.everlywell.com/blog/sti-testing/are-any-stds-not-curable/')
lisa = Member.create!(name: 'Lisa', website_url: 'https://www.everlywell.com/blog/womens-health/how-do-you-boost-fertility/')
bart = Member.create!(name: 'Bart', website_url: 'https://www.everlywell.com/blog/colon-cancer/2021-health-care-trends/')

MemberShortUrlJob.perform_now(homer.id, homer.website_url)
MemberPullHeadingsJob.perform_now(homer.id, homer.website_url)
MemberShortUrlJob.perform_now(marge.id, marge.website_url)
MemberPullHeadingsJob.perform_now(marge.id, marge.website_url)
MemberShortUrlJob.perform_now(lisa.id, lisa.website_url)
MemberPullHeadingsJob.perform_now(lisa.id, lisa.website_url)
MemberShortUrlJob.perform_now(bart.id, bart.website_url)
MemberPullHeadingsJob.perform_now(bart.id, bart.website_url)

homer.befriend(marge)
marge.befriend(homer)
homer.befriend(lisa)
lisa.befriend(homer)
homer.befriend(bart)
bart.befriend(homer)
lisa.befriend(bart)
bart.befriend(lisa)
